# Header
menu:
  All: /
  Development: /categories/Development/index.html
  Culture: /categories/Culture/index.html
  Daily: /categories/Daily/index.html
  Product: /categories/Product/index.html
  #About: /about
  #Contact: /contact

# Favicon
favicon_url:

# Default Image for Posts
default_cover_image: images/default.jpg

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
email_url: 
twitter_url: https://twitter.com/Koosjn?lang=en
facebook_url: https://www.facebook.com/profile.php?id=100011494121449
instagram_url: https://www.instagram.com/koosjn/
linkedin_url: https://www.linkedin.com/in/david-koo-302616a7/
dribbble_url:
github_url: https://github.com/Koosj
googleplus_url:
behance_url:
fivehundredpx_url:

# Disqus comments
disqus_shortname: on-the-code
