# Header
menu:
  All: /
  MINI: /categories/MINI/index.html
  Product: /categories/Product/index.html
  #About: /about
  #Contact: /contact

# Favicon
favicon_url:

# Default Image for Posts
default_cover_image: images/default.jpg

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
email_url: 
twitter_url: 
facebook_url: https://www.facebook.com/profile.php?id=100011494121449
instagram_url: 
linkedin_url: 
dribbble_url:
github_url: https://github.com/Koosj
googleplus_url:
behance_url:
fivehundredpx_url:

# Disqus comments
disqus_shortname: on-the-code
